create table if not exists public.ai_anomalies (
  id bigint generated by default as identity primary key,
  zone_key text not null,
  event_type text not null,
  score numeric(10,2) not null,
  risk_level text not null,
  danger_increment numeric(10,3) not null,
  district text,
  pincode text,
  latitude double precision,
  longitude double precision,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_ai_anomalies_created_at on public.ai_anomalies (created_at desc);
create index if not exists idx_ai_anomalies_zone_key on public.ai_anomalies (zone_key);

create table if not exists public.ai_zone_risk (
  zone_key text primary key,
  district text,
  pincode text,
  latitude double precision,
  longitude double precision,
  score numeric(10,2) not null,
  risk_level text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_alerts (
  id bigint generated by default as identity primary key,
  zone_key text not null,
  pincode text,
  title text not null,
  message text not null,
  severity text not null,
  score numeric(10,2) not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_ai_alerts_created_at on public.ai_alerts (created_at desc);
